### ISSUE TITLE
HTML support

### ISSUE THREAD

**Issue by egreb** [vegarnorman/frontend#1]
Hello

I was wondering if you are planning to make this support automatic reload at HTML changes as well.

cheers

**Comment by vegarnorman** [comment]
Hi,

It's set up so it should reload on HTML changes, so long as the HTML files are located in the `public` folder. Have you had problems with the browser not reloading on HTML changes?

**Comment by egreb** [comment]
Yes. The pages does not reload at html changes. Tested at the index.html file. 
Otherwise it works as intended.

**Comment by evenh** [comment]
I can confirm the same behaviour at my machine @egreb :+1:

**Comment by vegarnorman** [comment]
Yup, it was set up listening to the wrong path. Changes have been committed now. Thanks, guys!
